version: '3.8'

services:

  server:
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    container_name: animal-server
    depends_on:
      - animal-db
    environment:
      - PGDATABASE=animal-database
      - PGUSER=animal
      - PGPASSWORD=animal-collector@8392
      - PGHOST=animal-db
    ports:
      - 8003:8000
    volumes:
      - ./server:/usr/src/app

  animal-db:
    container_name: animal-db
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=animal
      - POSTGRES_PASSWORD=animal-collector@8392
    expose:
      - 5432
    volumes:
      - animal-db:/var/lib/postgresql/data

volumes:
  animal-db: