# Generated by Django 3.1.4 on 2021-05-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210502_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranimal',
            old_name='picture_url',
            new_name='file',
        ),
    ]
