# Generated by Django 3.1.4 on 2021-03-09 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animal_useranimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranimal',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
