# Generated by Django 3.1.4 on 2021-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210502_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranimal',
            name='file',
            field=models.URLField(),
        ),
    ]
