# Generated by Django 3.1.4 on 2021-03-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useranimal_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_name',
            field=models.CharField(max_length=255),
        ),
    ]
