# Generated by Django 3.1.4 on 2021-03-12 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210310_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranimal',
            name='users',
        ),
        migrations.AddField(
            model_name='useranimal',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
